INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Talk (0)");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hera");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ares");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Athena");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hermes");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Demeter");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dionysus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aphrodite");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Apollo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Artemis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eros");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Pan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Harmonia");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hebe");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nike");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Asclepius");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hecate");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bia");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Deimos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Phobos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Alecto");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Megaera");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tisiphone");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vesta");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Thanatos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Rhode");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nyx");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Enyo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Atropos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Clotho");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lachesis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gaia");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Iris");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chronus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Terminus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Janus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sylvanus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Odin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Thor");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Loki");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Baldr");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hodur");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hermod");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Frey");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Freya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Forseti");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bragi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hel");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Frigga");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tyr");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Njord");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mimir");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Urd");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Skuld");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Verandi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Volla");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vidar");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ratatoskr");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ra");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Khepri");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Osiris");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anubis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Isis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Horus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Set");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bast");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bes");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sobek");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nephthys");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hathor");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sekhmet");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Thoth");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Serqet");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nepri");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hapi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Taweret");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Khonsu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Medjed");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kebechet");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anhur");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Pakhet");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Heh");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dua");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Min");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ptah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Pan-Ku");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shennong");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nu Wa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yu Huang");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sun Wukong");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hou Tou");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Guan Yu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tian Mu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lei Gong");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shou Hsing");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xi Wangmu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kui Xing");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Zhu Rong");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nezha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yen-Lo Wang");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Zao Shen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Choy Sun Yeh");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chang'e");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eight Immortals");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Izanagi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Izanami");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Amaterasu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tsukuyomi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Susanoo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bishamon");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hotei");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ebisu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Daikokuten");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Banzaiten");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Fukurokuju");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jurōjin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Inari");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kaminari");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Raijin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Fujin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kagutsuchi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ame-No-Mi-Kumari");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Amatsu-Mikaboshi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kuzenbo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"The Dagda");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Balor");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Angus");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anpao");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Cerridwen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Cernunnos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gwynn");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Danu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Leir");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Fuamnach");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bodb Derg");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lugh");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nuada");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Morrigan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Arawn");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Badb");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Brigit");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Boann");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Taranis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Artio");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Epona");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Cairbre");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Carman");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dub");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dother");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dian");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Brahman");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vishnu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shiva");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kali-Ma");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ganesha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ratli");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yama");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Indra");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Agni");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Parvati");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lakshmi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Maya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kartikeya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ahura Mazda");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mithras");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ahriman");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ametertat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Atar");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Asha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Armaiti");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kshathra Vairya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vohu Manah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Haurvatat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Zurvan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gitche Manitou");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hotamintanio");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Haokah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Malsumis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Calumet");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nokomis");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nanabozho");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Iktomi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Owayodata");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tawa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tomazooma");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dzeharlons");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kaiti");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Azeban");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jiibayaabooz");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hodiak");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Narya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nanuq");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Negafok");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kadlu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nelvanna");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Turoq");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sedna");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tekkeitsertok");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aipalovik Agloolik");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Quetzalcoatl");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tezcatlipoca");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Huitzilopochtli");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tlaloc");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Coatlicue");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xipe Totec");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ozomatli");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xochipilli");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xochiquetzal");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Michtlantecuhtli");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xolotl");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tonatiuh");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Huehuecoyotl");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Itzamna");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hunab Ku");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ixchel");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Wayep");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chaac");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ah Muzen Cab");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Awilix");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hun Batz");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Acat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kukulkan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ah Kin Xoc");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ixcacao");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Acan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ek Chuah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Xbalanque");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hunaphu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ah-Puch");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Buluc Chabtan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mam");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Inti");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chasca");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Catequil");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kon");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Pachamama");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Viracocha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Supay");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mama Cocha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mama Quilla");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Urcuchillay");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Axomamma");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kane Milohai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ku");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lono");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kanaloa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Papa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ragni");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Namaka");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Whiro");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Pele");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Poliahu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"B'ngudja");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ukanipo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kamohoalii");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Apukohai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lakakane");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kuape");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Maui");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Altjira");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Baiame");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Julunggul");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Daramulum");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mamaragan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gnowee");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Marmoo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Narahdarn");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Wambeen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Bathala");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Apo Laki");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mayari");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Amihan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anitun");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aswang");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Detinos");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aman Sinaya");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Apo Angin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tengri");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ulgen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vaat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kuara");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ay");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Koyash");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Erlik");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gesar");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kyazaghan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Umay");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kayra");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kurmez");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Murgen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Kubai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ak Ana");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ay-Ata");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Gun Ana");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yel Ana");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yel Ata");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Berkut");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aisyt");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Su Ana");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Su Ata");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Od Ana");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Od Ata");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yer Tanry");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Etuhen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jaiuk");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Alaz");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Baianai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Adaghan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Akbugha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shalyk");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Inehsit");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Uren");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Qovaq");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Zarlik");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Zada");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ukulan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Izih");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chokqu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Talai");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Svarog");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Veles");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Perun");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Stribog");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Svarozvich");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Milda");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Saule");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Marzanna");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Dazhbog");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Laima");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lada");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Svantovit");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Chernobog");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Buluku");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Avlekete");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ogun");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Shango");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Damballah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anansi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eschu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Oshun");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ghekre");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lusa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Mahu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Legba");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Baron Samedi");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Annu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ba'al");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eriskegal");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Inanna");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Martu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nergal");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ningal");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Saja");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ninhursag");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tammuz");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Marduk");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tiamat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Apsu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ukko");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Äkräs");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nyyrikki");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tapio");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tuoni");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Vammatar");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ilmarinen");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ahti");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Akka");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ajatar");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Lempo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hwanin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Munsin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nulgupjisin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Cheuksin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Eopsin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jowangsin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Magu");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sosamsin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Teojusin");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ungnyeo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jumong");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sumyeong-Jangja");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yondung Halmoni");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Allah");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Allat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Aluzza");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Manat");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Hubal");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Wadd");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Suwa'");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yaghuth");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ya'uq");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nasr");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Nuha");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Tupa");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Sume");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Guaraci");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jaci");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Ceuci");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Akuanduba");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Iara");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yeba Belo");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Jurupari");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Anhanga");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yorixiriamori");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Yahweh");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Satan");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Saint Michael");
INSERT INTO `characters` (`id`,`name`) VALUES (UUID(),"Saint Gabriel");
